language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
env:
  global:
    - COVERAGE_CMD="coverage run -m"
    - COVERAGE_DEP="coverage"
  matrix:
    - WRAPT_DISABLE_EXTENSIONS=1
    - IRRELEVANT=
install:
  - pip install tox coveralls
script:
  - tox --skip-missing-interpreters
after_script:
  - coverage combine
  - coveralls
