language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
env:
  global:
    - COVERAGE_CMD="coverage run -m"
    - COVERAGE_DEP=coverage
install:
  - pip install tox coveralls
script:
  # travis lacks python3.5
  - tox --skip-missing-interpreters
after_script:
  - coverage combine
  - coveralls
